sonar:
  enabled: true
  type: other
build:
  enabled: false
  type: library
  buildKit: default
sast:
  enabled: true
steps:
  - name: unit-tests
    image: 289208114389.dkr.ecr.us-east-1.amazonaws.com/picpay-dev/hyperf:php8.2-swoole5.1-pcov
    environment:
      COMPOSER_AUTH:
        from_secret: composer-auth
        key: COMPOSER_AUTH
    commands:
      - composer install
      - composer test

  - name: php-81
    runAfter:
      - unit-tests
    image: 289208114389.dkr.ecr.us-east-1.amazonaws.com/moonlight-images/php:8.1-pcov
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
      COMPOSER_AUTH:
        from_secret: composer-auth
        key: COMPOSER_AUTH
    commands:
      - rm -rf vendor/
      - composer install
      - composer test

  - name: php-82
    runAfter:
      - php-81
    image: 289208114389.dkr.ecr.us-east-1.amazonaws.com/moonlight-images/php:8.2-pcov
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
      COMPOSER_AUTH:
        from_secret: composer-auth
        key: COMPOSER_AUTH
    commands:
      - rm -rf vendor/
      - composer install
      - composer test

  - name: php-83
    runAfter:
      - php-82
    image: 289208114389.dkr.ecr.us-east-1.amazonaws.com/moonlight-images/php:8.3-pcov
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
      COMPOSER_AUTH:
        from_secret: composer-auth
        key: COMPOSER_AUTH
    commands:
      - rm -rf vendor/
      - composer install
      - composer test
