version: '3'
services:
  hyperf-metric:
    container_name: hyperf-metric
    image: hyperf-commons
    build:
      context: .
      args:
        COMPOSER_AUTH: ${COMPOSER_AUTH}
    volumes:
      - .:/opt
    networks:
      - hyperf

networks:
  hyperf:
    driver: bridge
