#!/usr/bin/env sh

CMD=$(echo ${1:-help} | tr '-' '_')
ARGS=${@:2}

build() {
    docker-compose build hyperf-metric $ARGS
}

composer() {
    docker-compose run --rm hyperf-metric -c "composer $ARGS"
}

coverage() {
    if [ $# -eq 0 ]; then
        docker-compose run --rm hyperf-metric -c "composer test:coverage:clover"    
    else
            case "$1" in
                "clover")
                    docker-compose run --rm hyperf-metric -c "composer test:coverage:clover"
                    ;;
                "html")
                    PORT=${2:-8888}
                    open "http://localhost:$PORT"
                    docker-compose run --rm -p $PORT:$PORT hyperf-metric -c "composer test:coverage:html && php -S 0.0.0.0:$PORT -t tests/reports"
                    ;;
                *)
                    echo "Coverage report format unknown: $1"
                    ;;
            esac
    fi
}

logs() {
    docker-compose logs -f $ARGS
}

sh() {
    if [ $# -eq 0 ]; then
        docker-compose run --rm hyperf-metric
    else
        docker-compose run --rm hyperf-metric -c "$ARGS"
    fi
}

help() {
    echo "Usage: run [command] [args]"
    echo ""
    echo "Commands:"
    echo "  help         Show this help message"
    echo "  build        Build docker image"
    echo "  composer     Run composer"
    echo "  coverage     Show coverage"
    echo "  logs         Show logs"
    echo "  sh           Run shell"
}

$CMD $ARGS